import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Muftsabazaar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
<div className="space">
  <div className="ship">
    <div className="ship-rotate">
      <div className="pod"></div>
      <div className="fuselage"></div>
    </div>
  </div>
  <div className="ship-shadow"></div>
  <div className="mars">
    <div className="tentacle"></div>
    <div className="flag">
      <div className="small-tentacle"></div>
    </div>
    <div className="planet">
      <div className="surface"></div>
      <div className="crater1"></div>
      <div className="crater2"></div>
      <div className="crater3"></div>
    </div>
  </div>
  <div className="test"></div>
</div>
    </div>
  );
}
