import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Muftsabazaar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <article className="main-article post-520 post type-post status-publish format-standard has-post-thumbnail hentry category-how-to tag-export-mysql-database-table-to-excel-file tag-mysql-table-to-excel-in-php tag-mysql-to-excel">
        <section className="post-content">
          <div className="text">
            <div className="show">
              <li className="h2toc">
                <a href="#what_is_vender_assessment">
                  What is Vender Assessment?
                </a>
              </li>
              <li className="h2toc">
                <a href="#is_vender_assessment_mandatory_for_all_the_sellers">
                  Is Vender Assessment mandatory for all the sellers?
                </a>
              </li>
              <li className="h2toc">
                <a href="#how_can_i_get_vendor_assessment_exemption">
                  How Can I get Vendor Assessment Exemption?
                </a>
              </li>
              <li className="h2toc">
                <a href="#full_process_of_vendor_assessment">
                  Full Process of Vendor Assessment
                </a>
              </li>
              <li className="h2toc">
                <a href="#upload_oem_authorization_document_and_fill_all_detail">
                  Upload OEM authorization document and fill all detail
                </a>
              </li>
              <li className="h4toc">
                <a href="#login_to_gem_seller_account">
                  Login To Gem Seller Account
                </a>
              </li>
              <li className="h4toc">
                <a href="#open_vendor_assessment_exemption_tab">
                  Open Vendor Assessment Exemption Tab
                </a>
              </li>
              <li className="h4toc">
                <a href="#choose_who_you_are_manufacturer_or_reseller">
                  Choose Who You are Manufacturer or Reseller
                </a>
              </li>
              <li className="h4toc">
                <a href="#select_format_type_for_a_vendor_assessment_exemption">
                  Select format type for a vendor assessment exemption
                </a>
              </li>
              <li className="h4toc">
                <a href="#select_category_for_vendor_assessment">
                  Select Category for vendor assessment
                </a>
              </li>
              <li className="h4toc">
                <a href="#upload_your_nsic_certificate">
                  Upload Your NSIC Certificate
                </a>
              </li>
              <li className="h4toc">
                <a href="#click_to_submit_for_vendor_assessment">
                  Click to Submit for Vendor assessment
                </a>
              </li>
              <li className="h4toc">
                <a href="#open_the_vendor_assessment_tab_again">
                  Open the Vendor assessment Tab again
                </a>
              </li>
            </div>
            <p>
              GeM (<strong>Government E-Marketplace</strong>) is the most
              popular online buying platform for Government. GeM Is the most
              trusted, Secure, and Corruption Free Platform for buying anything.
              The most important thing is here buyer can do anything which wants
              like: he can purchase with his own specification and he also fixes
              his budget here right.
            </p>
            <p>
              Now let's move our topic which is How Can I take vendor Assessment
              free. But before it knows some things About Vendor Assessment.
            </p>
            <h2 id="what_is_vender_assessment">What is Vender Assessment?</h2>
            <p>
              The Vendor Assessment is a facility, mandatory for OEMs, with
              certain exemptions. The Vendor Assessment Policy covers three
              distinct aspects of vendors that are captured and validated.
            </p>
            <ol>
              <li>
                The vendors profile related information, which includes Personal
                identity, Nature of business entity, Financial and Professional
                status. These are validated through online integration.
              </li>
              <li>
                the Second aspect is relating to the business entity&rsquo;s
                profile with respect to the supplying capacity and past
                experiences. This is applicable only for Original Equipment
                Manufacturers (OEM).
              </li>
              <li>
                the Third aspect is the performance of vendors in the GeM
                portal. Once registered and validated either as an OEM or
                authorized re-seller, the credentials are dynamically validated
                based on their performance and rating on the platform.
              </li>
              <li>
                The validity of the Vendor Assessment shall be 3years from the
                date of issue. The seller can also apply for a fresh assessment
                at his choice at any time on payment of a requisite fee. After
                receipt of the new Vendor Assessment report, the old VA report
                will become invalid. For sellers who have got Vendor assessments
                done from agencies other than QCI, Vendor Assessment validity is
                two years from the date of assessment.
              </li>
            </ol>
            <h2 id="is_vender_assessment_mandatory_for_all_the_sellers">
              Is Vender Assessment mandatory for all the sellers?
            </h2>
            <p>
              No, Vendor Assessment is not mandatory for all the sellers, it is
              only mandatory for all OEMs &amp; resellers ( in select
              categories) unless they come under exempted category.
            </p>
            <h2 id="how_can_i_get_vendor_assessment_exemption">
              How Can I get Vendor Assessment Exemption?
            </h2>
            <p>
              As an OEM, you can initiate Vendor Assessment Exemption from your
              account profile by furnishing the required information &amp;
              document with respect to Vendor Assessment Exemption. This
              information would be collected through an online form and upon
              successful submission, QCI would validate the information and the
              document uploaded by the OEM in the 2 working days. Once the
              details are validated and approved, the OEM shall be exempted from
              the Vendor Assessment.
            </p>
            <p>Also, Read</p>
            <p>
              <a href="https://muftsabazaar.com/blog/post/how-to-make-l1-on-gem">
                How to make Your product L1 on gem
              </a>
            </p>
            <p>
              <a href="https://muftsabazaar.com/blog/post/how-to-list-products-on-gem-government-e-marketplace">
                How to list and sell your product and gem
              </a>
            </p>
            <p>
              <a href="https://muftsabazaar.com/blog/post/what-is-filter-on-gem-government-e-marketplace-how-to-make-filter-on-gem">
                What is Filter
              </a>
            </p>
            <h2 id="full_process_of_vendor_assessment">
              Full Process of Vendor Assessment
            </h2>
            <h4 id="login_to_gem_seller_account">
              Login To Gem Seller Account
            </h4>
            <p>
              Before getting started you need an approved GeM seller account.
              now login to GeM as a seller by going on GeM Login Portal.
            </p>
            <p>
              Enter GeM User Id and the captcha and then click on submit then
              enter your password to login successfully.
            </p>
            <p>
              <img
                src="https://admin.muftsabazaar.com/uploads/253login1.jpeg"
                alt="Gem Login"
                width="800"
                height="293"
              />
            </p>
            <h4 id="open_vendor_assessment_exemption_tab">
              Open Vendor Assessment Exemption Tab
            </h4>
            <p>On the top right corner, you will see Your Profile Name.</p>
            <p>
              Go to My Account &gt; My Action &gt;{" "}
              <a
                className="tab-section-content ng-scope ng-binding current"
                translate="$a$.user.profile.vendor_assessments.label"
              >
                Vendor Assessments &gt; Assessment Exemption &gt; Create
                Exemption Request.
              </a>
            </p>
            <p>
              <img
                src="https://admin.muftsabazaar.com/uploads/699Screenshot (114).jpeg"
                alt="Vendor assessment"
                width="800"
                height="476"
              />
            </p>
            <h4 id="choose_who_you_are_manufacturer_or_reseller">
              Choose Who You are Manufacturer or Reseller
            </h4>
            <p>
              Choose here who you are I am the Manufacturer I am Going forward
              as a Manufacturer or OEM.
            </p>
            <p>
              <img
                src="https://admin.muftsabazaar.com/uploads/634Screenshot (116).jpeg"
                alt="OEM on Gem"
                width="800"
                height="400"
              />
            </p>
            <h4 id="select_format_type_for_a_vendor_assessment_exemption">
              Select format type for a vendor assessment exemption
            </h4>
            <p>
              There are five types of exemption formats I have NSIC so that's
              why I am going with this if you have another of them then you can
              go with that easily.
            </p>
            <p>
              <img
                src="https://admin.muftsabazaar.com/uploads/1000Screenshot (117).jpeg"
                alt="Vendor assessment"
                width="800"
                height="368"
              />
            </p>
            <h4 id="select_category_for_vendor_assessment">
              Select Category for vendor assessment
            </h4>
            <p>
              Now you have to select a category for vendor assessment request
              which category you want.
            </p>
            <p>
              <img
                src="https://admin.muftsabazaar.com/uploads/624Screenshot (118).jpeg"
                alt="Category for Vendor assessment"
                width="800"
                height="460"
              />
            </p>
            <h2 id="upload_oem_authorization_document_and_fill_all_detail">
              Upload OEM authorization document and fill all detail
            </h2>
            <p>
              Fill all the details about the category and also fill sold detail
              of you category there are not required detail of selling on the
              gem you put your all detail's of government selling or private
              hospital details and click submit.
            </p>
            <p>
              <img
                src="https://admin.muftsabazaar.com/uploads/250Screenshot (121).jpeg"
                alt="NSIC Cirtificate"
                width="800"
                height="391"
              />
            </p>
            <h4 id="upload_your_nsic_certificate">
              Upload Your NSIC Certificate
            </h4>
            <p>
              <img
                src="https://admin.muftsabazaar.com/uploads/308Screenshot (122).jpeg"
                alt="Vendor Assessment"
                width="800"
                height="382"
              />
            </p>
            <h4 id="click_to_submit_for_vendor_assessment">
              Click to Submit for Vendor assessment
            </h4>
            <p>Click to submit vendor assessment and go to your profile.</p>
            <p>
              <img
                src="https://admin.muftsabazaar.com/uploads/66Screenshot (124).jpeg"
                alt="Complete Vendor assessment"
                width="800"
                height="313"
              />
            </p>
            <h4 id="open_the_vendor_assessment_tab_again">
              Open the Vendor assessment Tab again
            </h4>
            <p>
              Go to your profile and open the Vendor assessment tab Now you can
              see you Vender assessment request is done and it will take 24 to
              48 hour for doing this process.
            </p>
            <p>
              <img
                src="https://admin.muftsabazaar.com/uploads/488Screenshot (125).jpeg"
                alt="Vender assessment done"
                width="800"
                height="539"
              />
            </p>
            <p>
              Thank you for reading this post please tell us your problem in the
              gem below comment section or you will also call us (
              <strong>8920344991) </strong>we are here for your help.
            </p>
            <p>Also, Visit our other website.</p>
            <p>
              <a href="https://www.twitter-trends.muftsabazaar.com/">
                see what's trending on Twitter trends
              </a>
            </p>
            <p>
              <a href="https://ifsc.muftsabazaar.com/">
                see your bank IFSC and other details
              </a>
            </p>
            <p>
              <a href="https://www.fancytextgenerator.muftsabazaar.com/">
                make your name stylish with our fancy text generator
              </a>
            </p>
            <p> </p>{" "}
          </div>
          <div className="clear"></div>

          <div className="share-buttons section">
            <h5 className="title small">Share Article:</h5>
            <div className="epcl-share-bottom">
              <a
                className="facebook epcl-button circle"
                rel="nofollow"
                href="https://www.facebook.com/sharer/sharer.php?u=https://muftsabazaar.com/blog/post/how-can-i-get-vendor-assessment-exemption-for-free-vendor-assessment-exemption-free"
                onclick="window.open(this.href, 'facebook-share','width=580,height=296');return false;"
              >
                <i className="fa fa-facebook"></i>
              </a>

              <a
                className="twitter epcl-button circle"
                rel="nofollow"
                href="http://twitter.com/share?text=How Can I Get Vendor Assessment Exemption for Free | Vendor Assessment Exemption Free&url=https://muftsabazaar.com/blog/post/how-can-i-get-vendor-assessment-exemption-for-free-vendor-assessment-exemption-free"
                onclick="window.open(this.href, 'twitter-share', 'width=550,height=235');return false;"
              >
                <i className="fa fa-twitter"></i>
              </a>

              <a
                className="email epcl-button circle"
                rel="nofollow"
                href="mailto:?subject=How Can I Get Vendor Assessment Exemption for Free | Vendor Assessment Exemption Free&body=https://muftsabazaar.com/blog/post/how-can-i-get-vendor-assessment-exemption-for-free-vendor-assessment-exemption-free"
                target="_blank"
              >
                <i className="fa fa-envelope"></i>
              </a>

              <a
                className="whatsapp epcl-button circle"
                rel="nofollow"
                href="https://api.whatsapp.com/send?text=https://muftsabazaar.com/blog/post/how-can-i-get-vendor-assessment-exemption-for-free-vendor-assessment-exemption-free"
                data-action="share/whatsapp/share"
              >
                <i className="fa fa-whatsapp"></i>
              </a>
            </div>
            <div className="clear"></div>
          </div>
        </section>

        <div className="bottom-tags">
          <i className="remixicon remixicon-price-tag-3-line"></i>
          gem, How to complete my vender assessment, vender assessment free,
          vendor assessment complete course{" "}
        </div>
      </article>
    </div>
  );
}
